### PR TITLE
Article page of New York Times page

### PR DESCRIPTION
**Pull request by krys2fa**
This is a cloned page of the New York Times original article page using HTML and CSS.

### CODE REVIEW

**Comment by lekegitrepo** [comment]
### Hi @krys2fa and @Rumbie-Mudzie7 👏 👏 
### _Well done, you did a good job. The page looks great but you still need to implement some requirements before the project can be approved._

**_1. The NY Times logo should be a link_** ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

**_2. The footer should have a fixed position_** (it sticks to the bottom part of the screen) ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0)) **_like the original_** 👇 
newyork times

**_3. Try to improve your Pull Request message._**

**_4. Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`)_** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

**_5. Fix the inflation theory section_** 👇 

image

**_if you have any doubts or questions contact me on slack_**

### _You used good commit messages_ ⭐️ 

### Reviewed by: _Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Require changes.

**Comment by krys2fa** [comment]
Hi @lekegitrepo, thanks for the feedback. Please find the implemented changes to the feedback.

Kind regards,

**Comment by uryelah** [comment]
Hello **Chris Amanor** & **Rumbie Mudziviri**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Great job fixing the required changes from the last review!🌟**

Your project is almost there but there are still some spacing issues you need to work on before going to the next one. Hang in there, you got this! 💪

---------    

## Required Changes 🏗 👷‍♀ 

- [ ] Pay attention to the font size and color of the captions, text under article images and video.Try to style it close to the[ original site.](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)
**Clone**
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times(4)
**Original version:**
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun(3)

**Clone**
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times(5)
**Original version:**
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun(4)

-----

- [ ] The footers last row of links should be aligned horizontally without wrapping.
**Clone:**
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times(2)
**Original version:**
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun(1)
-----

- [ ] Make sure the 'Theory of inflation' title has enough margin between itself and the main article text. Make sure the text weight and font also look similar to the original ones.
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times(1)

**Compare the font weights below:**
**Clone:**
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times(3)
**Original version:**
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun(2)
-----

- [ ] Make sure the articles on the 'Editors pick' aside are spaced correctly and have a similar font size to the original ones.

Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times(6)
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun(5)

-----

- [ ] Make sure you style the icons at the start and bottom of the article in a similar way to the original ones, rounded border with background and a similar shade of gree.


Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun - The New York Times
Screenshot_2020-04-06 Space Ripples Reveal Big Bang’s Smoking Gun

-----

- [ ] [OPTIONAL] Use an svg image for the logo, you can get it from inspecting the original page. SVGs scale better and are easier to style than normal images.




-----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by christianotieno** [comment]
## Pull Request under review by Christian Otieno (TSE)

**Comment by christianotieno** [comment]
> This is a cloned page of the New York Times original article page using HTML and CSS.

## [RECOMMENDATION]: 
- Good job with the summary. We can always improve on it next time by highlighting what we have carried out in the project's PR to guide the reviewer on what has been achieved so far. 😄

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job @Rumbie-Mudzie7  & @krys2fa! :+1:
- [ ] The commented out h4 tag on line 744 can be removed as well.
- Other than that, you can now merge to master and I wish you all the very best in your next tasks. 🎖 

##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Comment by Rumbie-Mudzie7** [comment]
Good day

Thank you for the positive review.

kinds regards

**Pull request merged**
